# Generated by Django 3.1.3 on 2020-11-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201119_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='usertenant',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('id', 'usertenant')},
        ),
    ]
